import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bruno Cerecetto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full h-screen">
        <h1 className="text-6xl">Site under construction 👷🏼‍♂️</h1>
        <iframe
          title="legendary"
          width="50%"
          height="50%"
          src="https://www.youtube.com/embed/C19US6rqqAo?controls=0&autoplay=1&mute=0&loop=1"
          frameBorder={0}
          allow="autoplay"
          allowFullScreen
        />
      </main>
    </div>
  );
};

export default Home;
