import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bruno Cerecetto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <iframe
          title="barney"
          src="https://giphy.com/embed/ekkKldHuLW90Y"
          width="480"
          height="333"
          frameBorder="0"
          className="giphy-embed"
        />
      </main>
    </div>
  );
};

export default Home;
